<a href="https://colab.research.google.com/github/wesley34/comp3414_course_material/blob/master/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1VZbJc2zjK6XQTovVjGzCHLS-m9sRdiCG#scrollTo=Tur-zo-qjfMh_)

# **NumPy - Why do we need it?**

NumPy stands for numerical python. The NumPy library provides us a multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 

NumPy is a very important library that we usually used in the field of Data Science and Machine Learning.

Following code demonstrates the advantage of using ndarray. We dont't have to do operation on a list in a elementwise manner:

In [ ]:
import numpy as np

arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([2, 4, 6, 8, 10])

print(arr1*arr2)

[ 2 12 30 56 90]


# **Prerequistite**
We use pip to install the numpy package:
```
 pip install numpy
```


# **Arrays in NumPy**
Arrays in Numpy is know as ndarray. The number of dimension of ndarray is known as the rank of the array. The size of the array of each dimension is known as the shape of the array. Details of ndarray will be explained in the following sections:



**Creating NumPy array**

We can create ndarray several ways. E.g. python list, python tuple, **np.zeros()**, **np.full().**

In [5]:
import numpy as np

# Creating ndarray using a python list
list1 = [1, 2, 3, 4, 5]
example1_array = np.array(list1)
print(example1_array)
# Creating ndarray using two python lists
list2 = [6, 7, 8, 9, 10]
list3 = [11, 12, 13, 14, 15]
example2_array = np.array([list2, list3])
print(example2_array)


# Creating ndarray using a python tple
tuple = (1, 2, 3, 4, 5)
example3_array = np.array(tuple)
print(example3_array)

# Creating ndarray wwith np.zeros(), it will set the value of each element in the array with all zeros.
# Here we define the size of each dimension of the array as 2
array = np.zeros((2, 2))
print(array)

# Creating ndarray wwith np.full(), it will set the value of each element in the array with a constant value.
# Here we define the type of each elements as complex type.
array = np.full((2, 2), 1, dtype='complex')
print(array)


[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[1 2 3 4 5]
[[0. 0.]
 [0. 0.]]
[[1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]]


https://numpy.org/devdocs/user/absolute_beginners.html