<a href="https://colab.research.google.com/github/wesley34/comp3414_course_material/blob/master/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1VZbJc2zjK6XQTovVjGzCHLS-m9sRdiCG#scrollTo=Tur-zo-qjfMh_)

# **NumPy - Why do we need it?**

NumPy stands for numerical python. The NumPy library provides us a multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 

NumPy is a very important library that we usually used in the field of Data Science and Machine Learning.

Following code demonstrates the advantage of using ndarray. We dont't have to do operation on a list in a elementwise manner:

In [ ]:
import numpy as np

arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([2, 4, 6, 8, 10])

print(arr1*arr2)

[ 2 12 30 56 90]


# **Prerequistite**
We use pip to install the numpy package:
```
 pip install numpy
```


# **Arrays in NumPy**
Arrays in Numpy is know as ndarray. The number of dimension of ndarray is known as the rank of the array. The size of the array of each dimension is known as the shape of the array. Details of ndarray will be explained in the following sections:



**1. Creating NumPy array**

We can create ndarray several ways. E.g. python list, python tuple, **np.zeros()**, **np.full().**

In [25]:
import numpy as np

# Creating ndarray using a python list
list1 = [1, 2, 3, 4, 5]
example1_array = np.array(list1)
print(example1_array)
# Creating ndarray using two python lists
list2 = [6, 7, 8, 9, 10]
list3 = [11, 12, 13, 14, 15]
example2_array = np.array([list2, list3])
print("\n", example2_array)


# Creating ndarray using a python tple
tuple = (1, 2, 3, 4, 5)
example3_array = np.array(tuple)
print("\n", example3_array)

# Creating ndarray wwith np.zeros(), it will set the value of each element in the array with all zeros.
# Here we define the size of each dimension of the array as 2
array = np.zeros((2, 2))
print("\n", array)

# Creating ndarray wwith np.full(), it will set the value of each element in the array with a constant value.
# Here we define the type of each elements as complex type.
array = np.full((2, 2), 1, dtype='complex')
print("\n", array)

#Creating ndarray with random number
array = np.random.rand(3, 4)
print("\n", array)

[1 2 3 4 5]

 [[ 6  7  8  9 10]
 [11 12 13 14 15]]

 [1 2 3 4 5]

 [[0. 0.]
 [0. 0.]]

 [[1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]]

 [[0.34300307 0.72588013 0.04074876 0.43051503]
 [0.92828587 0.90390207 0.37290227 0.399111  ]
 [0.40656096 0.7012196  0.01360881 0.57332441]]


**2. Indexing NumPy Array**

Indexing can be done by either using slicing or using an array as an index. 

Noted that the first element is indexed by 0, while the last element is indexed by -1. Please take a look in following eamples.

In [ ]:
import numpy as np
list = [1, 2, 3, 4, 5]
example_array = np.array(list)
print(example_array)
# Indexing by using an array as an index
newArray = example_array[
    np.array([2, 0, -1, -4])
]
print("\n", newArray)
# Indexing by slicing, it is in the form [start:stop:step], the stop position is not included in slicing
newArray = example_array[1:-2:1]
print("\n", newArray)


[1 2 3 4 5]

 [3 1 5 2]

 [2 3]


Here will show another example about slicing and indexing of a mutidiemnsional array:

In [ ]:
import numpy as np
array = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [4, 5, 6, 7]
])
print(array)

# Slicing and indexing in 4x4 array
# Print first two rows and first two columns
print("\n", array[0:2, 0:2])

# Print all rows and last two columns
print("\n", array[:, 2:4])

# Print all column but middle two rows
print("\n", array[1:3, :])

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]

 [[1 2]
 [2 3]]

 [[3 4]
 [4 5]
 [5 6]
 [6 7]]

 [[2 3 4 5]
 [3 4 5 6]]


**3. Operations in NumPy Array**

**3.1. Basic Mathematical Operation**

We can perform some basic mathematical operations, e.g. addition, subtration, multiplication and division.

Following code demonstrates mathematical operations on NumpPy array.

In [ ]:
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
newArray = array1 + 2
print(newArray)

newArray1 = newArray * 2
print("\n", newArray1)

newArray2 = newArray + newArray1
print("\n", newArray2)


#We can use .sum() to find the sum of every element in a array
print("\n", newArray2.sum())

[[3 4 5]
 [6 7 8]]

 [[ 6  8 10]
 [12 14 16]]

 [[ 9 12 15]
 [18 21 24]]

 99


**3.2 Mathematical Function in NumPy**

Numpy also allows us to perform lots of different mathematical operations, E.g. trigonometric function(sine, cosine), logarithmic function, exponentail function. 


In [ ]:
import numpy as np

#Trigonometric Function
x = 0
print(np.sin(x))

x = np.pi / 2
print(np.sin(x))

x = np.pi / 4
print(np.sin(x))

#Logarithmic Function, noted that it is calculating the natural logarithm of all elements in the array
arr = [1, 3, 50]
logValues = np.log(arr)
print(logValues)

#Exponententail Function
arr = [1, 3, 50]
expValues = np.exp(arr)
print(expValues)

0.0
1.0
0.7071067811865475
[0.         1.09861229 3.91202301]
[2.71828183e+00 2.00855369e+01 5.18470553e+21]


# **Use Cases of NumPy in Data Science & Machine Learning**

In this part, we would like to demonstrate the use of Numpy library in doing some fundamental scientifc computations in Machine Learning.

We will first take a look at the use of NumPy **Linear Algebra** module.


**Finding Determinant, Transpose, Inverse, etc. of an array (Matrix)**


In [ ]:
array = np.array([
    [1, 3, 5],
    [2, 4, 6],
    [-3, 6, -9]
])
#Finding Rank
rank = np.linalg.matrix_rank(array)
print("Rank:", rank)

#Finding Determinant
determinant = np.linalg.det(array)
print("Determinant:", determinant)

#Finding Trace
trace = np.trace(array)
print("Trace:", trace)

#Finding Transpose
transpose = np.transpose(array)
print("Transpose:", transpose)

#Finding Inverse
inverse = np.linalg.inv(array)
print("Inverse:", inverse)

#Finding Eigenvalue and Eigenvectors
eigenVal, eigenVec = np.linalg.eig(array)
print("EigenValue:",eigenVal)
print("EigenVector:", eigenVec)

Rank: 3
Determinant: 47.999999999999986
Trace: -4
Transpose: [[ 1  2 -3]
 [ 3  4  6]
 [ 5  6 -9]]
Inverse: [[-1.5         1.1875     -0.04166667]
 [ 0.          0.125       0.08333333]
 [ 0.5        -0.3125     -0.04166667]]
EigenValue: [-10.20339462  -0.68312011   6.88651473]
EigenVector: [[-0.30850626 -0.94443436  0.57097257]
 [-0.33296586 -0.01721604  0.79783852]
 [ 0.891043    0.32824892  0.19350458]]


**Calculating Dot Product** 

In [ ]:
import numpy as np

v_a = 1 + 2j
v_b = 2 + 4j

vectorProduct = np.dot(v_a, v_b)
print("Dot Product of vector values  : ", vectorProduct)

Dot Product of vector values  :  (-6+8j)


**Solving Linear Matrix Equation**

In [22]:
import numpy as np

A = np.array([
    [1, 3],
    [2, 4]
])

b = np.array([
    [5],
    [6]
])

x = np.linalg.solve(A, b)
print(x)

[[-1.]
 [ 2.]]


Next, we will look at the usage of Numpy in **Fourier Transform**.Forurier Transform is often uses in decomposing a signal(function) into its constituent frequencies. Fourier Transform may have different applications. E.g. Fast large-integer and polynomial multiplication, Filtering Algorithm.

In [24]:
import numpy as np

#1D Fourier Transform
A = np.array([1, 3, 5, 7, 9])
result = np.fft.fft(A)
print("\n", result)

#2D Fourier Transform
A = np.array([
    [2, 4, 6, 8, 9],
    [1, 3, 5, 7, 9]
])
result = np.fft.fft2(A)
print("\n", result)


#N-D Fourier Transform
A = np.array([
    [2.3, 4.1, 6.5, 8, 9],
    [3, -1.2, 6, -2, -4]
])
result = np.fft.fftn(A)
print("\n", result)


 [25.+0.j         -5.+6.8819096j  -5.+1.62459848j -5.-1.62459848j
 -5.-6.8819096j ]

 [[ 54.         +0.j         -10.30901699+12.81276269j
   -9.19098301 +2.66141171j  -9.19098301 -2.66141171j
  -10.30901699-12.81276269j]
 [  4.         +0.j          -0.30901699 -0.95105652j
    0.80901699 -0.58778525j   0.80901699 +0.58778525j
   -0.30901699 +0.95105652j]]

 [[ 31.7        +0.j          -7.22558014 -1.82338546j
    4.62558014 +7.41621639j   4.62558014 -7.41621639j
   -7.22558014 +1.82338546j]
 [ 28.1        +0.j          -3.53966744+12.90709507j
  -12.26033256 -4.50909046j -12.26033256 +4.50909046j
   -3.53966744-12.90709507j]]


# **Congratuations! You have completed this chapter.**

Following is the official documentation of NumPy, you may go take a look and learn more about the usage of NumPy. Good Luck :)

https://numpy.org/devdocs/user/absolute_beginners.html