<a href="https://colab.research.google.com/github/wesley34/comp3414_course_material/blob/master/ch_9_basic_reinforcement_learning/DQNIntrodution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Welcome to DQN starter kit, you will learn how to make a deep reinforcemnt learning with simulator here

### I would provide intuition with some math in a very brief sense

1.   To help you to at least know what is nerual network in a very brief sense
2.   To help you to know how to make a simulaotr
3.   To help you to code a very simple DQN


### Step 1 : Simulator
### Explore on https://gym.openai.com/docs/

### Keyword


1.   state : observation from the environment(simulator)
2.   action : agents' action
3.   reward : scores you get from the simulator with some special calculation




In [ ]:
# required libaray
import gym

In [ ]:
env = gym.make("CartPole-v0") # env stands for environment

In [ ]:
print(env.observation_space) # "bot" observes 4 things in this simulator
## you may check the meaning behind the numbers -> go explore yourself now

Box(4,)


In [ ]:
env.reset() # environment reset that means we open a new round of game (as the bot will die)
# it will return a new observation (size of 4)

array([ 0.0207832 ,  0.02326512,  0.0427209 , -0.00041564])

In [ ]:
print(env.action_space) # bot has 2 option on moving

Discrete(2)


In [ ]:
print(env.step(0)) # move first action
print(env.step(1)) # move second action

(array([ 0.01779965, -0.36814642,  0.04882127,  0.61127589]), 1.0, False, {})
(array([ 0.01043672, -0.17373961,  0.06104679,  0.33436089]), 1.0, False, {})


In [ ]:
# this is the meaning behind the return
observation, reward , is_done, extra_info = env.step(0)

In [ ]:
# reset the env before start
total_reward = 0.0
env.reset()
for _ in range(1000):
  # if you want to render the things
  # env.render() if cannot be run in colab but you may render it with normal IDE or special tatics in colab :)
  act = env.action_space.sample()
  obs, reward, is_done ,_ = env.step(act) # no extra info for this one
  total_reward += reward
  if is_done: # when you die you end 
    break
# if you get 200+ that means you are super lucky ! 
# good luck if you get 60+
# otherwise please keep looking :>
print(total_reward)

18.0


## Deep learning
#### Not much math here or it is another course :)

*   We use deep learning for modelling in DQN, you may also use others and you may explore them : what is the good or bad things of those algorithm
*   (Explore) Loss function , it calculates how much infomation you ignore or how bad it is your prediction result compare to the actual one. The common one is called mean square error : (L2 loss): 1/2 * (prediciton-real)^2
*   (Explore) Backward propagation , Intuition :  Base on you loss , it will use "Math" to correct you model parameter
*   (Explore) model parameter , or weightings: It is used to multiply the incoming data, so it will keep updating with backward propagation
*   (Explore) activation function: it helps you to filter "useless" data or provide non-linearlity to the model as the problem is always not a linear problem. (There are many usage for activation function not limit to this 2)


---
The flow on Deep learning

*   Data -> model -> prediction -> correct the model -> repeat ( basic flow of machine learning)
*   We only focus on modelling as the data preprocessing part in our problem is not much important at this moment (thats another statistic course :>)
*   We focus on model
*   (Data)-> multiply with weighings -> activation function -> new Data -> repeat (Common practise, but you may design a complex structure with spliting / routing / ...)
*   The data and te weightings are in matrix form , hence the size of the data can change easily : Data is 10 * 9 , weight is 9 * 1 , outcome is 10 * 9 * 9 * 1 = 10*1
*   Eventually, it will output a prediction 
*   We do not know what it is inside , or what is it doing, aka black box machine learning, (but indeed we can :> )


---
check some photo here to help you understanding https://www.newworldai.com/what-is-deep-learning-nature-of-machine-learning-and-beauty-of-deep-neural-networks/ 





## Converge
#### why the answer will come out
https://ml-cheatsheet.readthedocs.io/en/latest/gradient_descent.html

*   Gradient Descent 
*   (Explore , again it will be another course :> )There are many topics and skills related to them
*   Intuition : You want to buy a stock , you want to buy at the loweset. Similarly, we have cost in model, either maximize it or minimize it, we want to find out that point (local / Global). Gradient Descent helps us to draw a line to lead us to find the goal point given that we do not know where the goal point of the cost.
*   Check the math , it should not be difficult :> And please at least understand stochastic gradient descent, if better please understand stochastic in a brief sense



In [ ]:
## but it takes you a lot of time to tunning, fine-tunning and even create a new architecture
## the most common type architecture will be cnn,rnn,encoder ...
## and for each type there are a lot of implementations and creation, you may explore more but I think you already know all of them :>
## if possible please read the math on it and try to understand the backward propagation in a math sense which takes you the knowledges in
## partial-D

## Deep Learning + Gym + reinforcement learning ==>  deep reinforcemnt learning

In [ ]:
### Now we will create a deep learning model for the simulator 
### we will use pytorch here
### some explanation will be made
### tensorflow will be use later, as pytorch is more dynamic and good for reinforcement learning framework

In [ ]:
import torch
import torch.nn as nn
import numpy

In [ ]:
class DQN(nn.Module): #extend nn.module
  def __init__(self,observation_shape,action_shape): # constructor:
    super(DQN,self).__init__() # call parent constructor

    # we make a simple cnn architecture
    # nn.Sequntial is used to make a model
    # the layer will follow this setting to run 

    self.convolution_net = nn.Sequential( 
        nn.Conv2d(input_shape[0],32,kernel_size=7,stride=4), # check CNN yourself :>
        nn.ReLU(), # activation function  , check it youself :> , it is a light strategy to clear some not important message
        nn.Conv2d(32,64,kernel=4,stride=2),# btw, nn.Conv2d(input_channel,output_channel,kernel_size,stride_number) , channel means size , you should know and check it yourself :>
        nn.ReLU(),
        nn.Conv2d(64,64,kernel_size=3),
        nn.ReLU(),
    )
    # optional 
    # no batch norm, no pooling , have nothing in later preprocess, I m irresponsible as you know, check it yourself!
    # check why we need batch_norm, pooling , kinds of pooling , etc ... if you want to know more
    # check stride effect, check dilation , check variance on graphics ... if you want to know more
    
    
  
    conv_out_size = self._get_conv_output_shape(input_shape)

    self.fully_connected_net  = nn.Sequential(
        nn.Linear(conv_out_size,512),
        nn.ReLU(),
        nn.Linear(512,n.actions) # Linear means normal structure of Deep learning
    )

    def _get_conv_output_shape(self,shaoe):
      output = self.conv(torch.zeros(1,*shape)) # *shape is a special way to pass in argument, should be learnt in 1330 :>
      return int(np.prod(output.size)) #np.prod means product , here it means 1*output_size , as output.size is (1,output_size)
    # override function
    def forward(self,x):
      conv_out = self.convolution_net(x) # pass data to convolutional neural network
      # [channel,width,height] -> [channel,width*height] , as nn.Linear takes 2D data but cnn output 3d data
      conv_out = conv_out.view(x.size[0],-1)
      return self.fully_connected_net(x)


In [ ]:
# CNN
# in a brief sense,
# you have some images , you want to find some smaller images/pattern from them
# those pattern can help you understand more on the graph/pictures
# say, you wanna to detect from dog/cat
# the pattern formed due to deep learning is a cat-ear / dog-ear
# you know the pattern is in batches (that means a set of pattern)
# use those batches of pattern to compare with upcomming photo
# if the incomming photo matches with the cat-ear kernel -> then the probability of it being a cat will be increased
# if the incomming photo matches with the dog-ear kernel -> then the probability of it being a dog will be increased

In [ ]:
# create our agent now
class Agent:
  def __init__(self,env.exp_replay_buffer): # constructor
    self.env = env
    self.exp_buffer = exp_buffer
    # telling agent it is the start of the game
    self._reset()
  
  def _reset(self):
    self.state = env.reset()
    self.total_reward = 0
  
  def play_step(self,net,epsilon=0.0,device="cpu"):

    if np.random.random() < epsilon:
      action = env.action_space.sample()